CREATE TABLE ATLASBUS (
  INSERTED DATETIME NOT NULL, 
  ID INT(4) NOT NULL AUTO_INCREMENT, 
  DOCTYPE ENUM('PASSP_RU', 'PASSP_BY', 'CERT_OB_RU', 'CERT_OB_BY'), 
  DOCNUMBER VARCHAR(20), 
  PHONENUMBER VARCHAR(20),
  SEX ENUM('MALE', 'FEMALE'),
  SECTION ENUM('A', 'B', 'C'),  
  EMAIL VARCHAR(50), 
  NAME VARCHAR(30), 
  SURNAME VARCHAR(30), 
  PATRONYMIC VARCHAR(30), 
  BIRTHDATE DATE,
  IPV4 INT(4),
  BROWSER CHAR(100),
  LINK CHAR(32),
  PRIMARY KEY(ID), 
  KEY USER(EMAIL)
);

ALTER TABLE ATLASBUS CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;